### ISSUE TITLE
Валюта: пересчет цены

### ISSUE THREAD

**Issue by 2frags** [gadev/evoCart#2]
А как будет правильно пересчитывать цену, заданную в валюте по курсу из глобальной настройки вида [(user_currency)]?

В корзину можно передать курс дата-аттрибутом, но потом неясно как его включить в пересчет цены. Да и неправильно это как-то. 
В сниппете prepareEvoCart не получается модифицировать $data['price'] 
Непонятно где и на каком этапе можно модифицировать цены.
Спасибо!

**Comment by gadev** [comment]
в prepare вы можете создать любую новую переменную, типа $data[newprice] =
$data[price] * kurs. и в чанке выводить ее. курс, раз у вас хранится в
глобальных настройках, то и передавать ее не надо. получайте ее в сниппете
через getConfig. както так если в общих словах

ср, 12 дек. 2018 г. в 19:26, 2frags <notifications@github.com>:

**Comment by 2frags** [comment]
Спасибо! 
Переменную $data['newprice'] задаю в prepareEvoCart.
Вместо значения плейсхолдера в evoCartRow [+newprice+] выводится текст:  [+newprice+] 
И вообще никакие действия с $data['price'] в [prepareEvoCart](http://modx.im/blog/addons/5779.html#comment51215) никак ее не меняют в корзине.
Возможно дело в новых версиях MODx(1.4.6) и Doclister (2.4.0)
На каких версиях магазин сейчас работает?

**Comment by gadev** [comment]
да, прошу прощения, ошибка в прошлом комменте.
к выводу в корзине принудительно используется $data['tv.price'], поэтому изменять надо его.
т.е. в prepareEvoCart у вас должно быть что-то вроде 
`$data['tv.price'] = $data['tv.price'] * $modx->getConfig('user_currency');`

при этом в чанке evoCartRow все оставляете по-дефолту

**Comment by 2frags** [comment]
Да, $data['tv.price'] работает!
Спасибо)
